wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.0
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.13
    start_time: 1664444132.880269
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 23
      4: 3.8.13
      5: 0.13.0
      8:
      - 2
      - 5
